-- MySQL Script generated by MySQL Workbench
-- Mon May 11 13:06:37 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ZakarSpearMaster
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ZakarSpearMaster
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ZakarSpearMaster` DEFAULT CHARACTER SET utf8 ;
USE `ZakarSpearMaster` ;

-- -----------------------------------------------------
-- Table `ZakarSpearMaster`.`website`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZakarSpearMaster`.`website` ;

CREATE TABLE IF NOT EXISTS `ZakarSpearMaster`.`website` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(255) NOT NULL,
  `company` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZakarSpearMaster`.`search_people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZakarSpearMaster`.`search_people` ;

CREATE TABLE IF NOT EXISTS `ZakarSpearMaster`.`search_people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `born` DATETIME NOT NULL,
  `profile_picture` VARCHAR(255) NULL,
  `biography` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZakarSpearMaster`.`password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZakarSpearMaster`.`password` ;

CREATE TABLE IF NOT EXISTS `ZakarSpearMaster`.`password` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) NOT NULL,
  `hash_md5` CHAR(32) NULL,
  `hash_ripemd` CHAR(40) NULL,
  `hash_sha256` CHAR(64) NULL,
  `website_id` INT NOT NULL,
  `search_people_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `text_UNIQUE` (`text` ASC) VISIBLE,
  INDEX `fk_password_website1_idx` (`website_id` ASC) VISIBLE,
  INDEX `fk_password_search_people1_idx` (`search_people_id` ASC) VISIBLE,
  CONSTRAINT `fk_password_website1`
    FOREIGN KEY (`website_id`)
    REFERENCES `ZakarSpearMaster`.`website` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_password_search_people1`
    FOREIGN KEY (`search_people_id`)
    REFERENCES `ZakarSpearMaster`.`search_people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZakarSpearMaster`.`hashing_function`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZakarSpearMaster`.`hashing_function` ;

CREATE TABLE IF NOT EXISTS `ZakarSpearMaster`.`hashing_function` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `min_length` INT NULL,
  `max_length` INT NULL,
  `type` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZakarSpearMaster`.`website_has_hashing_function`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZakarSpearMaster`.`website_has_hashing_function` ;

CREATE TABLE IF NOT EXISTS `ZakarSpearMaster`.`website_has_hashing_function` (
  `website_id` INT NOT NULL,
  `hashing_function_id` INT NOT NULL,
  PRIMARY KEY (`website_id`, `hashing_function_id`),
  INDEX `fk_hashing_function_has_website_website1_idx` (`website_id` ASC) VISIBLE,
  INDEX `fk_hashing_function_has_website_hashing_function_idx` (`hashing_function_id` ASC) VISIBLE,
  CONSTRAINT `fk_hashing_function_has_website_hashing_function`
    FOREIGN KEY (`hashing_function_id`)
    REFERENCES `ZakarSpearMaster`.`hashing_function` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hashing_function_has_website_website1`
    FOREIGN KEY (`website_id`)
    REFERENCES `ZakarSpearMaster`.`website` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
